// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdsrController from "./adsr_controller"
application.register("adsr", AdsrController)

import AutowahController from "./autowah_controller"
application.register("autowah", AutowahController)

import BpmController from "./bpm_controller"
application.register("bpm", BpmController)

import CardController from "./card_controller"
application.register("card", CardController)

import ChoruController from "./choru_controller"
application.register("choru", ChoruController)

import CompressorController from "./compressor_controller"
application.register("compressor", CompressorController)

import DelayController from "./delay_controller"
application.register("delay", DelayController)

import DistortionController from "./distortion_controller"
application.register("distortion", DistortionController)

import EqController from "./eq_controller"
application.register("eq", EqController)

import FreeverbController from "./freeverb_controller"
application.register("freeverb", FreeverbController)

import FreeverberController from "./freeverber_controller"
application.register("freeverber", FreeverberController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import JazzController from "./jazz_controller"
application.register("jazz", JazzController)

import JcverbController from "./jcverb_controller"
application.register("jcverb", JcverbController)

import LimiterController from "./limiter_controller"
application.register("limiter", LimiterController)

import MultibandController from "./multiband_controller"
application.register("multiband", MultibandController)

import PageController from "./page_controller"
application.register("page", PageController)

import PannerController from "./panner_controller"
application.register("panner", PannerController)

import PassController from "./pass_controller"
application.register("pass", PassController)

import PasserController from "./passer_controller"
application.register("passer", PasserController)

import PhaserController from "./phaser_controller"
application.register("phaser", PhaserController)

import PingController from "./ping_controller"
application.register("ping", PingController)

import PopController from "./pop_controller"
application.register("pop", PopController)

import ReverbController from "./reverb_controller"
application.register("reverb", ReverbController)

import RockController from "./rock_controller"
application.register("rock", RockController)

import SynthController from "./synth_controller"
application.register("synth", SynthController)

import TremeloController from "./tremelo_controller"
application.register("tremelo", TremeloController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)

import VibratoController from "./vibrato_controller"
application.register("vibrato", VibratoController)

import VolsController from "./vols_controller"
application.register("vols", VolsController)
